name: build

on:
  pull_request:

  push:
    branches:
      - main
    tags:
      - v*

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.16, 1.x]

    name: Go ${{ matrix.go }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: make build

      - name: Example
        run: make example
